### ISSUE TITLE
使用163邮箱报错

### ISSUE THREAD

**Issue by zhangrj** [zabbix-book/zabbix_mail_with_graph#1]
send mail error:        (554, 'DT:SPM 163 smtp12,EMCowACnzwc_BjhcKMZmAQ--.20404S2 1547175487,please see http://mail.163.com/help/help_spam_16.htm?ip=218.94.104.2&hostid=smtp12&time=1547175487')

554 DT:SPM 发送的邮件内容包含了未被许可的信息，或被系统识别为垃圾邮件。请检查是否有用户发送病毒或者垃圾邮件；

有办法解决吗

**Comment by zhausong** [comment]
163 QQ  QQ企业邮箱 量过大都会被拦截 可以自建邮件服务器  如postfix
