### ISSUE TITLE
图形时间修改为一天

### ISSUE THREAD

**Issue by ryswork1993** [zabbix-book/zabbix_mail_with_graph#2]
大佬，您好：
如果想要发送的一天的图形怎么做啊

**Comment by zhausong** [comment]
https://github.com/zabbix-book/zabbix_mail_with_graph/blob/master/mail_with_graph.py#L90
relace  ```1h```  to ```1d```
```
 graph_url = "%s/chart.php?from=now-1d&to=now&itemids[]=%s"
```
